import React from 'react'


const FooterBar = ()=>{

    return(
    <div className="footerbar">
        <div id ="quote">
            <h2>Random Quote generated by the backend</h2>
        </div>
    </div>
    );
}

export default FooterBar